import React from 'react'
import Head from 'next/head'
import ContactForm from '../components/Contact'
import NavBar from '../components/NavBar.tsx'

const contact = () => {
  return (
    <div>
         <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <ContactForm/>
    </div>
  )
}

export default contact