import Head from 'next/head'
import Image from 'next/image'
import AboutGrid from '../components/AboutGrid'
import ContactForm from '../components/Contact'
import GridOne from '../components/GridOne'
import styles from '../styles/Home.module.css'

import Projects from '../components/Projects'

export default function Home() {
  return (
    <div>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       <GridOne/>
       <AboutGrid/>
       <Projects/>
       <ContactForm/>
    </div>
  )
}
