import React from 'react'
import Head from 'next/head'
import Projects from '../components/Projects'
import NavBar from '../components/NavBar.tsx'

const projects = () => {
  return (
    <div> 
        <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <NavBar/>
        <Projects/>
    </div>
  )
}

export default projects